version: '3'

services:
  mrdetective:
    container_name: mrdetective
    build:
      context: ../..
      dockerfile: Dockerfile
    environment:
      BUCKET_NAME: ${BUCKET_NAME}
      S3_REGION: ${S3_REGION}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      APP_SECRET: ${APP_SECRET}
      PG_DATABASE: ${PG_DATABASE}
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
    ports:
      - "5000:5000"